version: '3'
services:
  elasticsearch:
    image: 'ghcr.io/yp-middle-python-24/elasticsearch:8.7.0'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    ports:
      - '9200:9200'
    volumes:
      - elasticdata:/opt/app/elasticsearch/data
    restart: always

  redis:
    image: 'redis:7.0.10-alpine'
    env_file:
      - .env
    depends_on:
      - elasticsearch
    volumes:
      - redisdata:/data
    restart: always

  postgres:
    image: 'postgres:13'
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./pg_gump.sql:/docker-entrypoint-initdb.d/pg_gump.sql
      - postgres_volume:/var/lib/postgresql/data/
    restart: always

  etl:
    build:
      context: ./postgres_to_es
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis
      - postgres
    restart: always

volumes:
  elasticdata:
  redisdata:
  postgres_volume:
