version: '3'
services:
  elasticsearch:
    image: 'ghcr.io/yp-middle-python-24/elasticsearch:8.7.0'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    ports:
      - '9200:9200'
    volumes:
      - elasticdata:/opt/app/elasticsearch/data
    restart: always

  redis:
    image: 'redis:7.0.10-alpine'
    env_file:
      - .env
    depends_on:
      - elasticsearch
    volumes:
      - redisdata:/data
    restart: always

  db:
    image: postgres:13
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always

  etl:
    build:
      context: ./postgres_to_es
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis
      - db
    restart: always

volumes:
  postgres_data:
  elasticdata:
  redisdata:
